### ISSUE TITLE
kubernetes-anywhere v1.4 umbrella

### ISSUE THREAD

**Issue by mikedanese** [kubernetes/kubernetes-anywhere#127]
This is an umbrella issue to track the next work that needs to be done in kubernetes-anywhere.
- [ ] Implement weave net for control plane pods
- [ ] strawman contract for phases #133
- [ ] Move of cloud provider pod network (implement pod network with weave at least until kubenet is stable) #125
- [ ] Implement addon management #126
- [ ] Implement some sort of release process
- [ ] Run comformance tests in jenkins
- [ ] Fixup documentation and polish UX

cc @kubernetes/sig-cluster-lifecycle

**Comment by bgrant0607** [comment]
@mikedanese https://github.com/kubernetes/kube-deploy/tree/master/min-turnup is being merged into this repo, or vice versa?

**Comment by mikedanese** [comment]
kube-deploy/min-turnup will be deleted. The code has been copied over.
